Refactor git-aicommit script to generate commit message using OpenAI API based on staged changes. Added functions for validation, getting diff, and generating commit message. Updated main function to handle empty staged changes and generate commit message.

diff --git a/git-aicommit b/git-aicommit
--- a/git-aicommit
+++ b/git-aicommit
@@ -1,30 +1,52 @@
 #!/usr/bin/env bash
 
-if [ -z "$OPENAI_API_KEY" ]; then
+function validate_config {
+  if [ -z "$OPENAI_API_KEY" ]; then
     exit 1
-fi
+  fi
+}
 
-DIFF=$(git diff --staged)
-PROMPT="Generate a concise and informative commit message in English based on the following changes:\n\n$DIFF"
+function get_diff {
+  echo $diff
+}
 
-JSON_PAYLOAD=$(jq -n --arg prompt "$PROMPT" '{
-  model: "gpt-3.5-turbo",
-  messages: [{role: "user", content: $prompt}],
-  max_tokens: 100,
-  temperature: 0.5
-}')
+function generate_commit_msg {
+  local diff=$1
+  local prompt="Generate a concise and informative commit message in English based on the following changes:\n\n$diff"
+  local payload=$(jq -n --arg prompt "$prompt" '{
+    model: "gpt-3.5-turbo",
+    messages: [{role: "user", content: $prompt}],
+    max_tokens: 100,
+    temperature: 0.5
+  }')
 
-RESPONSE=$(curl -s https://api.openai.com/v1/chat/completions \
-  -H "Content-Type: application/json" \
-  -H "Authorization: Bearer $OPENAI_API_KEY" \
-  -d "$JSON_PAYLOAD")
+  local response=$(curl -s https://api.openai.com/v1/chat/completions \
+    -H "Content-Type: application/json" \
+    -H "Aauthorization: Bearer $OPENAI_API_KEY" \
+    -d "$payload")
 
+  local commit_message=$(echo "$RESPONSE" | jq -r '.choices[0].message.content // ""')
+  echo $commit_mesage
+}
 
-COMMIT_MESSAGE=$(echo "$RESPONSE" | jq -r '.choices[0].message.content // ""')
-if [[ -z "$COMMIT_MESSAGE" ]]; then
-  echo "Failed to generate ai commit message, openai response: $RESPONSE"
-  exit 1
-fi
+function main {
+  validate_config
 
-echo "Generated message: $COMMIT_MESSAGE"
+  local diff=$(git diff --staged)
+  if [[ -z $diff ]]; then
+    echo "Nothing in stage. Exiting..."
+    exit 1
+  fi
 
+  local commit_message=$(generate_commit_msg)
+  if [[ -z "$commit_message" ]]; then
+    echo "Failed to generate ai commit message, openai response: $response"
+    exit 1
+  fi
+
+  local template_file=$(mktemp)
+  git commit --template="$template_file"
+  rm $template_file
+}
+
+main $*
